add notify steps
rapidsai/jenkins-shared-library pull request #42
Opened 2022-05-10 14:04 UTC by AyodeAwe

This PR adds notify steps for our Jenkinsfiles builds.

2022-05-10 14:13 UTC, ajschmidt8 requested changes

2022-05-10 14:13 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +      githubNotify account: 'rapidsai', description: 'Build is unstable', repo: 'rmm', sha: "${GIT_COMMIT}", status: 'PENDING'
Few things:

- The `repo` value should be computed dynamically instead of hardcoded. since this will be used by all RAPIDS libraries. In a shell script, it can be obtained like this: `basename ${GIT_URL} .git`, where `GIT_URL` is provided by Jenkins. You might be able to find an equivalent for Groovy.

- I think the `PENDING` status should be moved right above the `steps()` call.

- I'm not sure how Jenkins defines `UNSTABLE` builds :thinking:. Unless you find a compelling reason for us to keep that conditional, I think we can probably remove the entire `finally {}` block and just use the `try` / `catch` blocks.

2022-05-10 19:40 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: 'rapidsai', description: 'Build has succeeded', repo: "${repo}", sha: "${GIT_COMMIT}", status: 'SUCCESS'
Can we compute the account (i.e. `rapidsai`) dynamically as well? It seems we might be able to gather that information from the `GIT_URL`.  We should avoid hardcoding these values whenever possible.

2022-05-10 20:06 UTC, AyodeAwe commented on vars/generateStage.groovy
> +    githubNotify account: 'rapidsai', description: 'Build has succeeded', repo: "${repo}", sha: "${GIT_COMMIT}", status: 'SUCCESS'
This one-liner looks good to me. Wdut?

`def ghAccount = git_url.substring(git_url.lastIndexOf('.com')+5, git_url.lastIndexOf("/${repo}"))`

2022-05-10 20:19 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: 'rapidsai', description: 'Build has succeeded', repo: "${repo}", sha: "${GIT_COMMIT}", status: 'SUCCESS'
seems like it could work to me.

2022-05-10 20:30 UTC, ajschmidt8 approved these changes
LGTM. Don't forget we should also move the `withCredentials` block to this shared library. I'll leave it up to you as to whether you want to include it in this PR or another.

2022-05-10 20:32 UTC, ajschmidt8 requested changes
wait. need to request changes

2022-05-10 21:13 UTC, ajschmidt8 requested changes

2022-05-10 21:13 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: 'Build is now pending', repo: "${repo}", sha: "${GIT_COMMIT}", status: 'PENDING'
We need to add a `context` for these GitHub statuses.

For reference, in the screenshot below, `1` is the `context` and `2` is the `description`. The contexts need to be unique and describe the build that is occurring. Let's use these formats for the build contexts:

```sh
build/cuda/amd64/11.5 # cpp build
build/python/3.8/cuda/amd64/11.5 # python build
test/cuda/amd64/11.2/driver-495/python/3.9/ubuntu18.04 # test stage
```

![image](https://user-images.githubusercontent.com/7400326/167722012-dafcb2e5-c469-4ae4-b64b-c5ece3e31fee.png)

2022-05-11 14:39 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} succeeded in ${(currentBuild.durationString as Integer) / 60000}", repo: "${repo} minutes", sha: "${GIT_COMMIT}", status:
```suggestion
    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} succeeded in ${(currentBuild.durationString as Integer) / 60000}", repo: "${repo}", sha: "${GIT_COMMIT}", status: 'SUCCESS', context: ctx
```

2022-05-11 14:42 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} is now pending", repo: "${repo}", sha: "${GIT_COMMIT}", status: 'PENDING', context: ctx
I have some concerns about using `GIT_COMMIT` here. If our pipelines are configured to run on merge-commits instead of PR head commits (which they currently are), then `GIT_COMMIT` will correspond to the merge-commit, which doesn't exist on the PR and therefore the status won't be properly set on the PR.

We may need to find another way to get the true hash of the commit that triggered the pipeline.

2022-05-11 14:45 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} is now pending", repo: "${repo}", sha: "${GIT_COMMIT}", status: 'PENDING', context: ctx
My comment above assumes that the `GIT_COMMIT` value here is the same one provided by Jenkins in the pipelines when you run `env`.

2022-05-11 15:29 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} is now pending", repo: "${repo}", sha: "${GIT_COMMIT}", status: 'PENDING', context: ctx
@AyodeAwe, from the plugin's README below, it seems that the following parameter values are inferred, which means we may be able to just omit them entirely: `credentialsId`, `repo`, `sha`, `account`. Let's try this approach.


- https://github.com/jenkinsci/pipeline-githubnotify-step-plugin#inferring-parameter-values

2022-05-11 15:30 UTC, AyodeAwe commented on vars/generateStage.groovy
> +    githubNotify account: "${ghAccount}", description: "Build ${BUILD_NUMBER} is now pending", repo: "${repo}", sha: "${GIT_COMMIT}", status: 'PENDING', context: ctx
Okay

2022-05-11 15:45 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    branch_pr_test: [
Should these key values also use the constants above? i.e. `BRANCH_PR_TEST_STAGE`

2022-05-11 15:45 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +  def ghAccount = git_url.substring(git_url.lastIndexOf('.com')+5, git_url.lastIndexOf("/${repo}"))
Let's clean up `git_url`, `repo`, and `ghAccount` since they're not being used anymore.

2022-05-11 15:45 UTC, ajschmidt8 commented on vars/generateStage.groovy
> +    githubNotify description: "Build ${BUILD_NUMBER} is now pending", status: 'PENDING', context: ctx
Last thing we should do here is add a `targetUrl` to all of the `githubNotify` steps so that users can click the GH Check link to navigate to the Jenkins build.

The environment variable `RUN_DISPLAY_URL` should have the correct URL address. Based on the article below, it seems that you can access it with `"${env.RUN_DISPLAY_URL}"`.

- https://embeddedartistry.com/blog/2017/12/28/jenkins-generating-blue-ocean-urls/

2022-05-11 16:48 UTC, ajschmidt8 approved these changes

2022-05-11 16:52 UTC, merged